version: '3.5'

######################################################
# DATABASE SERVICE
######################################################
services:
  psql:
    build:
      context: ./docker/psql-build
    env_file:
      ./cfg/build.ini
    container_name: psql
    ports:
      - 5432:5432
    volumes:
      - ./mnt/postgres/pg_data:/var/lib/postgresql/data
    networks:
      - net

######################################################
# AIRFLOW
######################################################

  airflow:
    build:
      context: ./docker/airflow-build
    env_file:
      ./cfg/build.ini
    depends_on:
      - psql
    restart: always
    container_name: airflow
    volumes:
     - ./mnt/airflow/dags:/usr/local/airflow/dags
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 60s
      retries: 10
    networks:
      - net


networks:
  net: